### ISSUE TITLE
Cant reconnect when IOError(early eof)/OpCode::Close occurs

### ISSUE THREAD

**Issue by raphaelsoul** [PrivateRookie/ws-tool#4]
Cannot reconnect by calling `client.handshake().await`.
receives `HandShakeFailed("incomplete handshake response")`

seems to be caused by TCP proxy stream not reconnect in method `handshake`.

Considering add a `reconnect` method on `Connection` struct to perform a full connection establish progress?

```
reconnecting... Connection { uri: wss://fstream.binance.com/stream?streams=ethusdt@ticker, mode: WSS, codec: DefaultFrameCodec { check_rsv: true }, stream: Tls(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:65397, peer: 127.0.0.1:8118, fd: 10 }) }, session: ClientSession { imp: ClientSessionImpl }, state: Stream }), certs: {}, state: Running, handshake_remaining: b"", proxy: Some(Proxy { socket: 127.0.0.1:8118, schema: Http }), protocols: [], extensions: [] }
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HandShakeFailed("incomplete handshake response")', synchronizer/src/lib.rs:207:50
stack backtrace:
```

**Comment by PrivateRookie** [comment]
In ws-tool, proxy connection is completed in `builder.build` method, it's a design trade off because I think handshake should perform websocket protocol handshake only, it should not care underlying transport. So, to reconnect binance wesocket, call `builder.build` method(build does not consume builder, it's `&self`) to generate new client,  call `hanshake` of new client and read message.

**Comment by raphaelsoul** [comment]
in my case, my Connection instance is wrapped in a Mutex so I can use it in two threads for sending pong opcode and read frames concurrently.

Yet I solved it by using `mem::replace` and replacing the old connection.

if you dont think it is necessary to implement a `reconnect` method. Just close the issue.
